[tool.ruff]
# Enable pycodestyle (E), pyflakes (F), and bugbear (B) rules
select = ["E", "F", "B"]

line-length = 88
ignore = ["E501"]

target-version = "py38"


[tool.ruff.flake8-quotes]
docstring-quotes = "double"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rsxX --showlocals --tb=native -p no:cacheprovider"
testpaths = ["tests"]


[tool.release]
github_user = "mozilla-services"
github_project = "socorro-submitter"
bugzilla_product = "Socorro"
bugzilla_component = "Infra"
main_branch = "main"
tag_name_template = "%%Y.%%m.%%d"


[tool.paul-mclendahand]
github_user = "mozilla-services"
github_project = "socorro-submitter"
main_branch = "main"
