---
version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.02

    steps:
      - checkout

      - run:
          name: Create version.json
          # yamllint disable rule:line-length
          command: |
            # create a version.json per
            # https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            # we don't dockerflow this, but it's handy to have a build artifact
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json
          # yamllint enable rule:line-length

      - store_artifacts:
          path: version.json

      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      - run:
          name: Build images
          command: make build-containers

      - run:
          name: Run linting and tests
          command: |
            # Run linting and tests without volume mounting because that
            # doesn't work in CircleCI
            ./bin/run_circle.sh
